# Dependencies
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - pygments.rb

# Permalinks
permalink:        pretty

# Setup
title:            Meniscectomia
tagline:          Tudo sobre a meniscectomia
description:      "Artigos sobre a meniscectomia"
url:              http://meniscectomia.com
baseurl:          /

author:
  name:           'Luís Ramalho'
  url:            http://luisramalho.com

paginate:         1
